client-21 integrity constraint vialtion
71m024/pradmin pull request #12
Opened 2023-05-15 14:05 UTC by SaraLuethi

https://github.com/Meisterwerk-GmbH/shopify-booqable-client/issues/21

2023-05-16 08:15 UTC, 71m024 requested changes
Das Required-Attribut finde ich schonmal gut so.  
Aber füge es am besten dann grad zu allen field-Komponenten hinzu.  
Jetzt musst du vermutlich einfach das ganze Speichern so umbauen, dass es `onSubmit` funktioniert und dann wird er vermutlich automatisch den Hinweis bringen, dass das Feld ausgefüllt sein muss.

2023-05-16 08:16 UTC, 71m024 requested changes

2023-05-16 08:16 UTC, 71m024 commented on src/ui/field/admin-select-field.jsx
> +          && <FormHelperText>Diese Feld muss ausgefüllt sein.</FormHelperText>}
Das `required` kannst du dann vermutlich einfach direkt dem `Select` Tag weitergeben.  
Würde dann einfach mal schauen was passiert, wenn man das Form mit `onSubmit` abschickt...
Ev kann stu dann den HelperText auch noch grad direkt auf dem `Select` Tag setzen.

2023-05-16 08:50 UTC, SaraLuethi commented
@SaraLuethi 

- [ ] bei allen fields das required hinzufügen
- [ ] speichern umbauen, so dass es mit submit funktioniert
- [ ] den Helper-Text auch gerade dem Select-Tag geben

2023-05-16 09:22 UTC, SaraLuethi commented
@71m024 @SaraLuethi 
Habe keine Ahnung wie man das ganze Angehen könnte. 
- Damit man ein required und onSubmit machen kann, muss es ein Form-Feld sein (oder Form-Control)
- Wo macht man dann die Überprüfung der Felder? 
- Wo gibt man den submitHandler mit?
- Wo setzt man die HelperText-Nachricht? und Wann?

2023-05-23 11:38 UTC, 71m024 requested changes
Ich habe es kurz ausprobiert und ohne die Hook-Form Library zum Laufen gebracht. Diese bitte wieder ausbauen.  

Jezt musst du nur noch schauen, die richtige Submit-Funktion aufgerufen wird unterschieden wird auf welchen Submit-Button geklickt wurde.  

In React gibt es ein wunderschönes Feature. Und zwar `refs`: https://react.dev/learn/manipulating-the-dom-with-refs  

Jetzt kannst du für beide Buttons so eine Referenz erstellen und dann in der Submit-Funktion via Submitter-Atribut vom Submit-Event checken welcher Button geklickt wurde.

2023-05-24 14:18 UTC, 71m024 commented on src/ui/crud/entity.form.jsx
> +  const saveAndBackRef = useRef(null);
Bitte `saveButton` und `saveAndBackButton` nennen.

2023-05-24 14:23 UTC, 71m024 commented on src/ui/crud/entity.form.jsx
> +  const onSubmit = (e) => {
Die Funktion beinhaltet noch duplicated code und ist aus meiner Sicht nicht Wirklich lesbar. War vorher besser und sollte nochmal überarbeitet werden.

2023-05-24 14:25 UTC, 71m024 commented on yarn.lock
Eigentlich sollte sich an diesem File nichts ändern. Wenn das nicht beabsichtig ist, bitte rückgängig machen.

2023-06-05 07:21 UTC, SaraLuethi commented
@71m024 habe die Funktion extrahiert und die Refs umbenennt; schaust du es noch mal an?

2023-06-12 14:22 UTC, 71m024 approved these changes
Ich habe die `onSubmit` Funktion nochmal massiv vereinfacht.  
Bitte schau dir meinen Commit kurz an und versuche in zukunft möglichst einfachen code zu schreiben.

2023-07-25 07:26 UTC, merged