several changes
71m024/pradmin pull request #2
Opened 2022-11-07 15:47 UTC by SaraLuethi

2022-11-21 17:20 UTC, 71m024 requested changes

2022-11-21 17:20 UTC, 71m024 commented on src/components/crud/entity.list.jsx
> +              initialState={initialState}
Brauchst du das und wenn ja wozu?

2022-11-21 17:20 UTC, 71m024 commented on src/components/field/admin-text-field.jsx
> -    setData({ ...data, [targetName]: numeric ? parseInt(newValue) : newValue });
Brauchst du jetzt das `numeric` prop garnicht mehr?  
Dann lösche es bitte wieder raus.

2022-11-22 13:27 UTC, 71m024 requested changes

2022-11-22 13:37 UTC, SaraLuethi commented on src/components/field/admin-text-field.jsx
> -    setData({ ...data, [targetName]: numeric ? parseInt(newValue) : newValue });
hast du gesagt, soll ich mal noch drin lassen...

2022-11-22 13:45 UTC, SaraLuethi commented on src/components/comparator.jsx
> +export default function comparator(key) {
habe es erledigt

2022-11-22 13:47 UTC, 71m024 approved these changes

2022-11-22 13:47 UTC, merged